---
services:
  database:
    image: koenkk/docker-compose-exercise-database
    # build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=movie123
    networks:
      - docker-compose-exercise
  webapp:
    image: koenkk/docker-compose-exercise-webapp
    # build: ./webapp
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - docker-compose-exercise
networks:
  docker-compose-exercise:
